version: '3.2'
services:
  data-warehouse:
    build: ./data-warehouse
    depends_on:
      - kafka
      - zookeeper
    command: node --inspect=0.0.0.0:9229 retreiverWarehouse.js --zookeeper="zookeeper:2181"
    ports:
      - '9229:9229'
  visualizer:
    build: ./Visualizer
    depends_on:
      - kafka
      - zookeeper
    command: node --inspect=0.0.0.0:9230 bin/www --zookeeper="zookeeper:2181"
    ports:
      - '9090'
      - '9230:9230'
  spark-submitter:
    depends_on:
      - spark-master
      - spark-worker
      - kafka
    ports:
      - '5005:5005'
    environment:
      - 'ENABLE_INIT_DAEMON=false'
    build: ./spark-submitter
