version: '3.2'
services:
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    ports:
      - '8080:8080'
      - '7077:7077'
    environment:
      - 'ENABLE_INIT_DAEMON=false'
      - 'INIT_DAEMON_STEP=setup_spark'
  spark-worker:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - '8081'
    environment:
      - 'ENABLE_INIT_DAEMON=false'
      - 'SPARK_MASTER=spark://spark-master:7077'
  postgres:
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_PASSWORD: psql
      POSTGRES_USER: postgres
      POSTGRES_DB: sparkdatabase
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./postgres/postgres-servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.dk
      PGADMIN_DEFAULT_PASSWORD: psql
    ports:
      - '5431:80'
